name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Jest tests with code coverage
      - name: Run Jest tests with coverage
        run: npm test -- --ci --coverage

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --headed --browser chrome
